#pragma once

enum JsTypes
{
	TYPE_OBJECT = 1,
	TYPE_NUMBER,
	TYPE_STRING,
	TYPE_BOOLEAN,
	TYPE_ARRAY,
	TYPE_FUNCTION,
	TYPE_CONSTRUCTOR,
	TYPE_NULL,
	TYPE_UNDEFINED,
    TYPE_INSTANCE,
	TYPE_UNKNOWN = 255,
};

enum JsNumberTypes
{
	TYPE_NUMBER_SBYTE = 1,
	TYPE_NUMBER_BYTE,
	TYPE_NUMBER_INT16,
	TYPE_NUMBER_UINT16,
	TYPE_NUMBER_INT32,
	TYPE_NUMBER_UINT32,
	TYPE_NUMBER_INT64,
	TYPE_NUMBER_UINT64,
	TYPE_NUMBER_SINGLE,
	TYPE_NUMBER_DOUBLE,
};
